#!/usr/bin/env bash

################################################################################
#
# Dit script kopieert TLS certificaten van de Let's Encrypt
# configuratiedirectory naar de OpenLDAP configuratiedirectory.
# Dit script wordt aangeroepen door de `copy-certs' deploy-hook van certbot.
#
# /usr/local/sbin/tls-openldap
#
# Meer info: https://www.librobert.net/boek/internet
#
################################################################################
#
# Copyright (c) 2020 Robert LA LAU < https://www.librobert.net/ >
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
################################################################################

dom="ldap.example.com"

[ -z "${systeem}" ] && {
	cat <<-EOM
		Gebruik:
		  env systeem=<os> $(basename $0)

		Waar <os> één van de volgende mogelijkheden is:
		  freebsd
		  ubuntu
		  centos

		Voorbeeld:
		  env systeem=freebsd $(basename $0)
EOM
	exit 1
}

case "${systeem}" in
	freebsd)
		src="/usr/local/etc/letsencrypt/live/${dom}/*.pem"
		dst="/usr/local/etc/openldap/certs"
		ug="ldap:ldap"
		;;
	ubuntu)
		src="/etc/letsencrypt/live/${dom}/*.pem"
		dst="/etc/ldap/certs"
		ug="openldap:openldap"
		;;
	centos)
		src="/etc/letsencrypt/live/${dom}/*.pem"
		dst="/etc/openldap/certs"
		ug="ldap:ldap"
		;;
	gentoo)
		src="/etc/letsencrypt/live/${dom}/*.pem"
		dst="/etc/openldap/ssl"
		ug="ldap:ldap"
		;;
	*)
		echo "Onbekend systeem."
		exit 1
		;;
esac

[ ! -d "${dst}" ] && {
	mkdir "${dst}" \
	  && chown ${ug} "${dst}" \
	  && chmod 750 "${dst}" \
	  || exit 1
}

cp -L ${src} ${dst}
chown ${ug} ${dst}/*
chmod 640 ${dst}/*
